### ISSUE TITLE
Car Doesn't Turn Even Though Code Tells it too

### ISSUE THREAD

**Issue by sdub18** [UMass-Amherst-Robotics/DreamTeam#11]
The Car is not pivoting right or left even though the code tells it too, I think this might have something to do with the power consumption of the four motors and the speed at which the batteries deplete. 

Will try to hook wire in a solid 9V into the car's H-Bridge via DC and see if that can power the motors continuously and without problems

**Comment by andrewtran10** [comment]
New battery implemented. Now motors rotate too fast. Need to implement software PWM to slowdown movement.
